name: Build and Upload Combined ZIP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Clone repo with submodules
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # 2. Create combined ZIP
      - name: Create combined ZIP
        run: |
          mkdir plugin_zip
          rsync -av --exclude='plugin_zip' ./ ./plugin_zip/
          cd plugin_zip
          zip -r ../Giswater_all.zip .

      # 3. Upload ZIP as artifact
      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: Giswater_all
          path: Giswater_all.zip
